uint8 request_type
string camera_topic_name
string image_path
string[] object_names
sensor_msgs/Image image
sensor_msgs/Image masks
BBox[] bounding_boxes
---
uint8 response_type
bool request_success
string image_path
sensor_msgs/Image image